# Uncomment the next line to define a global platform for your project
  # platform :ios, '9.0'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

target 'wzaNative' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wzaNative

  platform :ios, '9.0'
  #target 'wzaNative-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  target 'wzaNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'wzaNative-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for wzaNative-tvOS

  #target 'wzaNative-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

#end
